### ISSUE TITLE
Adding a measure while removing a different measure causes a runtime exception

### ISSUE THREAD

**Issue by gilmoreorless** [iangrunert/git-ratchet#22]
Adding or removing measures separately works, but it's the combination of the two that causes a problem.

To reproduce the error:

```sh
# Setup
mkdir ratchet-test && cd ratchet-test
git init

# Add two measures, works as expected
echo "First" > LOG.txt
git add LOG.txt && git commit -m "First"
echo -e "measure-A,5\nmeasure-B,4" | git ratchet -v check -w

# Remove a measure, works as expected
echo "Second" >> LOG.txt && git commit -am "Second"
echo -e "measure-A,5" | git ratchet -v check -w

# Add a new measure, works as expected
echo "Third" >> LOG.txt && git commit -am "Third"
echo -e "measure-A,5\nmeasure-C,3" | git ratchet -v check -w

# Add a new measure AND remove an old measure, THROWS AN EXCEPTION
echo "Fourth" >> LOG.txt && git commit -am "Fourth"
echo -e "measure-C,3\nmeasure-D,2" | git ratchet -v check -w
```

The error thrown is:

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/iangrunert/git-ratchet/store.CompareMeasures(0x228250, 0x6, 0xc20803ca21, 0x28, 0xc20804a700, 0x2, 0x2, 0xc20804a340, 0x2, 0x2, ...)
	/home/travis/gopath/src/github.com/iangrunert/git-ratchet/store/reader.go:250 +0x100c
github.com/iangrunert/git-ratchet/cmd.Check(0x228250, 0x6, 0x0, 0x3b0100, 0x225750, 0x3, 0xc208032601, 0x3b3bb0, 0xc208048000, 0x28efc0)
	/home/travis/gopath/src/github.com/iangrunert/git-ratchet/cmd/check.go:51 +0xfc4
main.func·002(0xc2080426c0, 0xc20803c720, 0x0, 0x3)
	/home/travis/gopath/src/github.com/iangrunert/git-ratchet/git-ratchet.go:42 +0x10d
github.com/spf13/cobra.(*Command).execute(0xc2080426c0, 0xc20803c660, 0x3, 0x3, 0x0, 0x0)
	/home/travis/gopath/src/github.com/spf13/cobra/command.go:603 +0x86b
github.com/spf13/cobra.(*Command).ExecuteC(0xc208042b40, 0xc2080426c0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/spf13/cobra/command.go:689 +0x501
github.com/spf13/cobra.(*Command).Execute(0xc208042b40, 0x0, 0x0)
	/home/travis/gopath/src/github.com/spf13/cobra/command.go:648 +0x3a
main.main()
	/home/travis/gopath/src/github.com/iangrunert/git-ratchet/git-ratchet.go:98 +0xc06
```

After some further testing, I've found that it only happens if the number of removed measures is greater than or equal to the number of added measures:

* Add 1, remove 1 – fails
* Add 1, remove 2 – fails
* Add 2, remove 1 – works

**Comment by iangrunert** [comment]
Nice find. I'm amazed we hadn't run into this case already.

I'll try and take a look at this in the next few days.

**Comment by dialmarco** [comment]
Disclaimer: I've never look at golang code before, and I'm not sure how to build / test, but quick look at the code:
```
for j < len(computedm) {
  computed := computedm[i]
  log.WARN.Printf("New measure found: %s", computed.Name)
  j++
}
```

it seems to me that the out of index is caused by ``computed := computedm[i]`` where it should be ``computed := computedm[j]``
